// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbmodels

import (
	"time"

	"jolly/backend/users/domain"
)

type UsersUser struct {
	UserUuid     domain.UserUUID
	Email        string
	Name         string
	Role         domain.Role
	CreatedAt    time.Time
	UpdatedAt    time.Time
	PasswordHash string
	AvatarUrl    *string
}
