// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbmodels

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
	"jolly/backend/users/domain"
)

type UsersPasswordResetToken struct {
	TokenHash string
	UserUuid  domain.UserUUID
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type UsersUser struct {
	UserUuid     domain.UserUUID
	Email        string
	Name         string
	Role         domain.Role
	CreatedAt    time.Time
	UpdatedAt    time.Time
	PasswordHash string
	AvatarUrl    *string
}
