// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package dbmodels

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
	"jolly/backend/users/domain"
)

const createResetToken = `-- name: CreateResetToken :exec
INSERT INTO users.password_reset_tokens (
	token_hash,
	user_uuid,
	expires_at,
	created_at
)
VALUES
	($1, $2, $3, $4)
`

type CreateResetTokenParams struct {
	TokenHash string
	UserUuid  domain.UserUUID
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) CreateResetToken(ctx context.Context, arg CreateResetTokenParams) error {
	_, err := q.db.Exec(ctx, createResetToken,
		arg.TokenHash,
		arg.UserUuid,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users.users (
	user_uuid,
	email,
	name,
	role,
	password_hash,
	avatar_url,
	created_at,
	updated_at
)
VALUES
	($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateUserParams struct {
	UserUuid     domain.UserUUID
	Email        string
	Name         string
	Role         domain.Role
	PasswordHash string
	AvatarUrl    *string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser,
		arg.UserUuid,
		arg.Email,
		arg.Name,
		arg.Role,
		arg.PasswordHash,
		arg.AvatarUrl,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteExpiredResetTokens = `-- name: DeleteExpiredResetTokens :exec
DELETE FROM users.password_reset_tokens
WHERE
	expires_at < $1
`

func (q *Queries) DeleteExpiredResetTokens(ctx context.Context, expiresAt pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, deleteExpiredResetTokens, expiresAt)
	return err
}

const deleteResetToken = `-- name: DeleteResetToken :exec
DELETE FROM users.password_reset_tokens
WHERE
	token_hash = $1
`

func (q *Queries) DeleteResetToken(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, deleteResetToken, tokenHash)
	return err
}

const getResetToken = `-- name: GetResetToken :one
SELECT
	token_hash,
	user_uuid,
	expires_at,
	created_at
FROM
	users.password_reset_tokens
WHERE
	token_hash = $1
LIMIT 1
`

func (q *Queries) GetResetToken(ctx context.Context, tokenHash string) (UsersPasswordResetToken, error) {
	row := q.db.QueryRow(ctx, getResetToken, tokenHash)
	var i UsersPasswordResetToken
	err := row.Scan(
		&i.TokenHash,
		&i.UserUuid,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT
	user_uuid, email, name, role, created_at, updated_at, password_hash, avatar_url
FROM
	users.users
WHERE
	user_uuid = $1
LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, userUuid domain.UserUUID) (UsersUser, error) {
	row := q.db.QueryRow(ctx, getUser, userUuid)
	var i UsersUser
	err := row.Scan(
		&i.UserUuid,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordHash,
		&i.AvatarUrl,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT
	user_uuid, email, name, role, created_at, updated_at, password_hash, avatar_url
FROM
	users.users
WHERE
	email = $1
LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (UsersUser, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i UsersUser
	err := row.Scan(
		&i.UserUuid,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordHash,
		&i.AvatarUrl,
	)
	return i, err
}

const updateUserAvatar = `-- name: UpdateUserAvatar :exec
UPDATE users.users
SET
	avatar_url = $2,
	updated_at = $3
WHERE
	user_uuid = $1
`

type UpdateUserAvatarParams struct {
	UserUuid  domain.UserUUID
	AvatarUrl *string
	UpdatedAt time.Time
}

func (q *Queries) UpdateUserAvatar(ctx context.Context, arg UpdateUserAvatarParams) error {
	_, err := q.db.Exec(ctx, updateUserAvatar, arg.UserUuid, arg.AvatarUrl, arg.UpdatedAt)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users.users
SET
	password_hash = $2,
	updated_at = $3
WHERE
	user_uuid = $1
`

type UpdateUserPasswordParams struct {
	UserUuid     domain.UserUUID
	PasswordHash string
	UpdatedAt    time.Time
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.UserUuid, arg.PasswordHash, arg.UpdatedAt)
	return err
}
