// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package dbmodels

import (
	"context"
	"time"

	"jolly/backend/users/domain"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO users.users (
	user_uuid,
	email,
	name,
	role,
	created_at,
	updated_at
)
VALUES
	($1, $2, $3, $4, $5, $6)
`

type CreateUserParams struct {
	UserUuid  domain.UserUUID
	Email     string
	Name      string
	Role      domain.Role
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser,
		arg.UserUuid,
		arg.Email,
		arg.Name,
		arg.Role,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getUser = `-- name: GetUser :one
SELECT
	user_uuid, email, name, role, created_at, updated_at
FROM
	users.users
WHERE
	user_uuid = $1
LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, userUuid domain.UserUUID) (UsersUser, error) {
	row := q.db.QueryRow(ctx, getUser, userUuid)
	var i UsersUser
	err := row.Scan(
		&i.UserUuid,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
