// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbmodels

import (
	"time"

	"jolly/backend/common"
	"jolly/backend/common/shared"
	"jolly/backend/orders/domain"
)

type OrdersOrder struct {
	OrderUuid   domain.OrderID
	CustomerID  common.UUID
	Currency    shared.Currency
	Status      domain.Status
	TotalCents  int64
	PlacedAtUtc time.Time
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type OrdersOrderLineItem struct {
	LineItemUuid   domain.LineItemUUID
	OrderUuid      domain.OrderID
	Sku            string
	Quantity       int32
	UnitPriceCents int64
}
