// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: orders.sql

package dbmodels

import (
	"context"
	"time"

	"jolly/backend/common"
	"jolly/backend/common/shared"
	"jolly/backend/orders/domain"
)

const getOrder = `-- name: GetOrder :one
SELECT
	order_uuid, customer_id, currency, status, total_cents, placed_at_utc, created_at, updated_at
FROM
	orders.orders
WHERE
	order_uuid = $1
LIMIT 1
`

func (q *Queries) GetOrder(ctx context.Context, orderUuid domain.OrderID) (OrdersOrder, error) {
	row := q.db.QueryRow(ctx, getOrder, orderUuid)
	var i OrdersOrder
	err := row.Scan(
		&i.OrderUuid,
		&i.CustomerID,
		&i.Currency,
		&i.Status,
		&i.TotalCents,
		&i.PlacedAtUtc,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderLineItems = `-- name: GetOrderLineItems :many
SELECT
	line_item_uuid, order_uuid, sku, quantity, unit_price_cents
FROM
	orders.order_line_items
WHERE
	order_uuid = $1
ORDER BY
	line_item_uuid
`

func (q *Queries) GetOrderLineItems(ctx context.Context, orderUuid domain.OrderID) ([]OrdersOrderLineItem, error) {
	rows, err := q.db.Query(ctx, getOrderLineItems, orderUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrdersOrderLineItem{}
	for rows.Next() {
		var i OrdersOrderLineItem
		if err := rows.Scan(
			&i.LineItemUuid,
			&i.OrderUuid,
			&i.Sku,
			&i.Quantity,
			&i.UnitPriceCents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveOrder = `-- name: SaveOrder :exec
INSERT INTO orders.orders (
	order_uuid,
	customer_id,
	currency,
	status,
	total_cents,
	placed_at_utc,
	created_at,
	updated_at
)
VALUES
	($1, $2, $3, $4, $5, $6, $7, $8)
`

type SaveOrderParams struct {
	OrderUuid   domain.OrderID
	CustomerID  common.UUID
	Currency    shared.Currency
	Status      domain.Status
	TotalCents  int64
	PlacedAtUtc time.Time
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) SaveOrder(ctx context.Context, arg SaveOrderParams) error {
	_, err := q.db.Exec(ctx, saveOrder,
		arg.OrderUuid,
		arg.CustomerID,
		arg.Currency,
		arg.Status,
		arg.TotalCents,
		arg.PlacedAtUtc,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const saveOrderLineItem = `-- name: SaveOrderLineItem :exec
INSERT INTO orders.order_line_items (
	line_item_uuid,
	order_uuid,
	sku,
	quantity,
	unit_price_cents
)
VALUES
	($1, $2, $3, $4, $5)
`

type SaveOrderLineItemParams struct {
	LineItemUuid   domain.LineItemUUID
	OrderUuid      domain.OrderID
	Sku            string
	Quantity       int32
	UnitPriceCents int64
}

func (q *Queries) SaveOrderLineItem(ctx context.Context, arg SaveOrderLineItemParams) error {
	_, err := q.db.Exec(ctx, saveOrderLineItem,
		arg.LineItemUuid,
		arg.OrderUuid,
		arg.Sku,
		arg.Quantity,
		arg.UnitPriceCents,
	)
	return err
}

const updateOrderStatus = `-- name: UpdateOrderStatus :exec
UPDATE orders.orders
SET
	status = $2,
	updated_at = $3
WHERE
	order_uuid = $1
`

type UpdateOrderStatusParams struct {
	OrderUuid domain.OrderID
	Status    domain.Status
	UpdatedAt time.Time
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) error {
	_, err := q.db.Exec(ctx, updateOrderStatus, arg.OrderUuid, arg.Status, arg.UpdatedAt)
	return err
}
