// Package http provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package http

import (
	"context"
	"encoding/json"
	"fmt"
	"mime/multipart"
	"net/http"
	"time"

	"jolly/backend/products/domain"

	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	strictecho "github.com/oapi-codegen/runtime/strictmiddleware/echo"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// CreateProduct defines model for CreateProduct.
type CreateProduct struct {
	Description string           `json:"description"`
	Name        string           `json:"name"`
	Status      ProductStatus    `json:"status"`
	Variants    *[]CreateVariant `json:"variants,omitempty"`
}

// CreateVariant defines model for CreateVariant.
type CreateVariant struct {
	Name       string `json:"name"`
	PriceCents int64  `json:"price_cents"`
	Sku        string `json:"sku"`
}

// ErrorDetail defines model for ErrorDetail.
type ErrorDetail struct {
	EntityId   *string `json:"entity_id,omitempty"`
	EntityType *string `json:"entity_type,omitempty"`
	ErrorSlug  *string `json:"error_slug,omitempty"`
	Message    *string `json:"message,omitempty"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Details *[]ErrorDetail `json:"details,omitempty"`
	Message string         `json:"message"`
	Slug    string         `json:"slug"`
}

// Product defines model for Product.
type Product struct {
	CreatedAt   time.Time `json:"created_at"`
	Description string    `json:"description"`
	Name        string    `json:"name"`

	// ProductUuid Unique product identifier
	ProductUuid ProductUUID   `json:"product_uuid"`
	Status      ProductStatus `json:"status"`
	UpdatedAt   time.Time     `json:"updated_at"`
	Variants    []Variant     `json:"variants"`
}

// ProductStatus defines model for ProductStatus.
type ProductStatus = domain.ProductStatus

// ProductUUID Unique product identifier
type ProductUUID = domain.ProductUUID

// UpdateProduct defines model for UpdateProduct.
type UpdateProduct struct {
	Description string        `json:"description"`
	Name        string        `json:"name"`
	Status      ProductStatus `json:"status"`
}

// UpdateVariant defines model for UpdateVariant.
type UpdateVariant struct {
	Name       string `json:"name"`
	PriceCents int64  `json:"price_cents"`
	Sku        string `json:"sku"`
}

// Variant defines model for Variant.
type Variant struct {
	CreatedAt  time.Time      `json:"created_at"`
	Images     []VariantImage `json:"images"`
	Name       string         `json:"name"`
	PriceCents int64          `json:"price_cents"`

	// ProductUuid Unique product identifier
	ProductUuid ProductUUID `json:"product_uuid"`
	Sku         string      `json:"sku"`
	UpdatedAt   time.Time   `json:"updated_at"`

	// VariantUuid Unique variant identifier
	VariantUuid VariantUUID `json:"variant_uuid"`
}

// VariantImage defines model for VariantImage.
type VariantImage struct {
	CreatedAt time.Time `json:"created_at"`

	// ImageUuid Unique variant image identifier
	ImageUuid VariantImageUUID `json:"image_uuid"`
	Position  int              `json:"position"`
	Url       string           `json:"url"`

	// VariantUuid Unique variant identifier
	VariantUuid VariantUUID `json:"variant_uuid"`
}

// VariantImageUUID Unique variant image identifier
type VariantImageUUID = domain.VariantImageUUID

// VariantUUID Unique variant identifier
type VariantUUID = domain.VariantUUID

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// Conflict defines model for Conflict.
type Conflict = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorResponse

// UploadVariantImageMultipartBody defines parameters for UploadVariantImage.
type UploadVariantImageMultipartBody struct {
	File *openapi_types.File `json:"file,omitempty"`
}

// UploadVariantImageParams defines parameters for UploadVariantImage.
type UploadVariantImageParams struct {
	Position *int `form:"position,omitempty" json:"position,omitempty"`
}

// CreateProductJSONRequestBody defines body for CreateProduct for application/json ContentType.
type CreateProductJSONRequestBody = CreateProduct

// UpdateProductJSONRequestBody defines body for UpdateProduct for application/json ContentType.
type UpdateProductJSONRequestBody = UpdateProduct

// AddVariantJSONRequestBody defines body for AddVariant for application/json ContentType.
type AddVariantJSONRequestBody = CreateVariant

// UpdateVariantJSONRequestBody defines body for UpdateVariant for application/json ContentType.
type UpdateVariantJSONRequestBody = UpdateVariant

// UploadVariantImageMultipartRequestBody defines body for UploadVariantImage for multipart/form-data ContentType.
type UploadVariantImageMultipartRequestBody UploadVariantImageMultipartBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List all products
	// (GET /products)
	ListProducts(ctx echo.Context) error
	// Create a new product
	// (POST /products)
	CreateProduct(ctx echo.Context) error
	// Delete a product
	// (DELETE /products/{product_uuid})
	DeleteProduct(ctx echo.Context, productUuid ProductUUID) error
	// Get product by UUID
	// (GET /products/{product_uuid})
	GetProduct(ctx echo.Context, productUuid ProductUUID) error
	// Update product details
	// (PUT /products/{product_uuid})
	UpdateProduct(ctx echo.Context, productUuid ProductUUID) error
	// Add a variant to a product
	// (POST /products/{product_uuid}/variants)
	AddVariant(ctx echo.Context, productUuid ProductUUID) error
	// Delete a variant
	// (DELETE /products/{product_uuid}/variants/{variant_uuid})
	DeleteVariant(ctx echo.Context, productUuid ProductUUID, variantUuid VariantUUID) error
	// Update a variant
	// (PUT /products/{product_uuid}/variants/{variant_uuid})
	UpdateVariant(ctx echo.Context, productUuid ProductUUID, variantUuid VariantUUID) error
	// Upload a variant image
	// (POST /products/{product_uuid}/variants/{variant_uuid}/images)
	UploadVariantImage(ctx echo.Context, productUuid ProductUUID, variantUuid VariantUUID, params UploadVariantImageParams) error
	// Delete a variant image
	// (DELETE /products/{product_uuid}/variants/{variant_uuid}/images/{image_uuid})
	DeleteVariantImage(ctx echo.Context, productUuid ProductUUID, variantUuid VariantUUID, imageUuid VariantImageUUID) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// ListProducts converts echo context to params.
func (w *ServerInterfaceWrapper) ListProducts(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListProducts(ctx)
	return err
}

// CreateProduct converts echo context to params.
func (w *ServerInterfaceWrapper) CreateProduct(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateProduct(ctx)
	return err
}

// DeleteProduct converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteProduct(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "product_uuid" -------------
	var productUuid ProductUUID

	err = runtime.BindStyledParameterWithOptions("simple", "product_uuid", ctx.Param("product_uuid"), &productUuid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter product_uuid: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteProduct(ctx, productUuid)
	return err
}

// GetProduct converts echo context to params.
func (w *ServerInterfaceWrapper) GetProduct(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "product_uuid" -------------
	var productUuid ProductUUID

	err = runtime.BindStyledParameterWithOptions("simple", "product_uuid", ctx.Param("product_uuid"), &productUuid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter product_uuid: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetProduct(ctx, productUuid)
	return err
}

// UpdateProduct converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateProduct(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "product_uuid" -------------
	var productUuid ProductUUID

	err = runtime.BindStyledParameterWithOptions("simple", "product_uuid", ctx.Param("product_uuid"), &productUuid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter product_uuid: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateProduct(ctx, productUuid)
	return err
}

// AddVariant converts echo context to params.
func (w *ServerInterfaceWrapper) AddVariant(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "product_uuid" -------------
	var productUuid ProductUUID

	err = runtime.BindStyledParameterWithOptions("simple", "product_uuid", ctx.Param("product_uuid"), &productUuid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter product_uuid: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.AddVariant(ctx, productUuid)
	return err
}

// DeleteVariant converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteVariant(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "product_uuid" -------------
	var productUuid ProductUUID

	err = runtime.BindStyledParameterWithOptions("simple", "product_uuid", ctx.Param("product_uuid"), &productUuid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter product_uuid: %s", err))
	}

	// ------------- Path parameter "variant_uuid" -------------
	var variantUuid VariantUUID

	err = runtime.BindStyledParameterWithOptions("simple", "variant_uuid", ctx.Param("variant_uuid"), &variantUuid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter variant_uuid: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteVariant(ctx, productUuid, variantUuid)
	return err
}

// UpdateVariant converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateVariant(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "product_uuid" -------------
	var productUuid ProductUUID

	err = runtime.BindStyledParameterWithOptions("simple", "product_uuid", ctx.Param("product_uuid"), &productUuid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter product_uuid: %s", err))
	}

	// ------------- Path parameter "variant_uuid" -------------
	var variantUuid VariantUUID

	err = runtime.BindStyledParameterWithOptions("simple", "variant_uuid", ctx.Param("variant_uuid"), &variantUuid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter variant_uuid: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateVariant(ctx, productUuid, variantUuid)
	return err
}

// UploadVariantImage converts echo context to params.
func (w *ServerInterfaceWrapper) UploadVariantImage(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "product_uuid" -------------
	var productUuid ProductUUID

	err = runtime.BindStyledParameterWithOptions("simple", "product_uuid", ctx.Param("product_uuid"), &productUuid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter product_uuid: %s", err))
	}

	// ------------- Path parameter "variant_uuid" -------------
	var variantUuid VariantUUID

	err = runtime.BindStyledParameterWithOptions("simple", "variant_uuid", ctx.Param("variant_uuid"), &variantUuid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter variant_uuid: %s", err))
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params UploadVariantImageParams
	// ------------- Optional query parameter "position" -------------

	err = runtime.BindQueryParameter("form", true, false, "position", ctx.QueryParams(), &params.Position)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter position: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UploadVariantImage(ctx, productUuid, variantUuid, params)
	return err
}

// DeleteVariantImage converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteVariantImage(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "product_uuid" -------------
	var productUuid ProductUUID

	err = runtime.BindStyledParameterWithOptions("simple", "product_uuid", ctx.Param("product_uuid"), &productUuid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter product_uuid: %s", err))
	}

	// ------------- Path parameter "variant_uuid" -------------
	var variantUuid VariantUUID

	err = runtime.BindStyledParameterWithOptions("simple", "variant_uuid", ctx.Param("variant_uuid"), &variantUuid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter variant_uuid: %s", err))
	}

	// ------------- Path parameter "image_uuid" -------------
	var imageUuid VariantImageUUID

	err = runtime.BindStyledParameterWithOptions("simple", "image_uuid", ctx.Param("image_uuid"), &imageUuid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter image_uuid: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteVariantImage(ctx, productUuid, variantUuid, imageUuid)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/products", wrapper.ListProducts)
	router.POST(baseURL+"/products", wrapper.CreateProduct)
	router.DELETE(baseURL+"/products/:product_uuid", wrapper.DeleteProduct)
	router.GET(baseURL+"/products/:product_uuid", wrapper.GetProduct)
	router.PUT(baseURL+"/products/:product_uuid", wrapper.UpdateProduct)
	router.POST(baseURL+"/products/:product_uuid/variants", wrapper.AddVariant)
	router.DELETE(baseURL+"/products/:product_uuid/variants/:variant_uuid", wrapper.DeleteVariant)
	router.PUT(baseURL+"/products/:product_uuid/variants/:variant_uuid", wrapper.UpdateVariant)
	router.POST(baseURL+"/products/:product_uuid/variants/:variant_uuid/images", wrapper.UploadVariantImage)
	router.DELETE(baseURL+"/products/:product_uuid/variants/:variant_uuid/images/:image_uuid", wrapper.DeleteVariantImage)

}

type BadRequestJSONResponse ErrorResponse

type ConflictJSONResponse ErrorResponse

type NotFoundJSONResponse ErrorResponse

type UnauthorizedJSONResponse ErrorResponse

type ListProductsRequestObject struct {
}

type ListProductsResponseObject interface {
	VisitListProductsResponse(w http.ResponseWriter) error
}

type ListProducts200JSONResponse []Product

func (response ListProducts200JSONResponse) VisitListProductsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListProducts401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListProducts401JSONResponse) VisitListProductsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type CreateProductRequestObject struct {
	Body *CreateProductJSONRequestBody
}

type CreateProductResponseObject interface {
	VisitCreateProductResponse(w http.ResponseWriter) error
}

type CreateProduct201JSONResponse Product

func (response CreateProduct201JSONResponse) VisitCreateProductResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateProduct400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateProduct400JSONResponse) VisitCreateProductResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateProduct401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CreateProduct401JSONResponse) VisitCreateProductResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type CreateProduct409JSONResponse struct{ ConflictJSONResponse }

func (response CreateProduct409JSONResponse) VisitCreateProductResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type DeleteProductRequestObject struct {
	ProductUuid ProductUUID `json:"product_uuid"`
}

type DeleteProductResponseObject interface {
	VisitDeleteProductResponse(w http.ResponseWriter) error
}

type DeleteProduct204Response struct {
}

func (response DeleteProduct204Response) VisitDeleteProductResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteProduct400JSONResponse struct{ BadRequestJSONResponse }

func (response DeleteProduct400JSONResponse) VisitDeleteProductResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type DeleteProduct401JSONResponse struct{ UnauthorizedJSONResponse }

func (response DeleteProduct401JSONResponse) VisitDeleteProductResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type DeleteProduct404JSONResponse struct{ NotFoundJSONResponse }

func (response DeleteProduct404JSONResponse) VisitDeleteProductResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetProductRequestObject struct {
	ProductUuid ProductUUID `json:"product_uuid"`
}

type GetProductResponseObject interface {
	VisitGetProductResponse(w http.ResponseWriter) error
}

type GetProduct200JSONResponse Product

func (response GetProduct200JSONResponse) VisitGetProductResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetProduct400JSONResponse struct{ BadRequestJSONResponse }

func (response GetProduct400JSONResponse) VisitGetProductResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetProduct401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetProduct401JSONResponse) VisitGetProductResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetProduct404JSONResponse struct{ NotFoundJSONResponse }

func (response GetProduct404JSONResponse) VisitGetProductResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type UpdateProductRequestObject struct {
	ProductUuid ProductUUID `json:"product_uuid"`
	Body        *UpdateProductJSONRequestBody
}

type UpdateProductResponseObject interface {
	VisitUpdateProductResponse(w http.ResponseWriter) error
}

type UpdateProduct200JSONResponse Product

func (response UpdateProduct200JSONResponse) VisitUpdateProductResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpdateProduct400JSONResponse struct{ BadRequestJSONResponse }

func (response UpdateProduct400JSONResponse) VisitUpdateProductResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type UpdateProduct401JSONResponse struct{ UnauthorizedJSONResponse }

func (response UpdateProduct401JSONResponse) VisitUpdateProductResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type UpdateProduct404JSONResponse struct{ NotFoundJSONResponse }

func (response UpdateProduct404JSONResponse) VisitUpdateProductResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type AddVariantRequestObject struct {
	ProductUuid ProductUUID `json:"product_uuid"`
	Body        *AddVariantJSONRequestBody
}

type AddVariantResponseObject interface {
	VisitAddVariantResponse(w http.ResponseWriter) error
}

type AddVariant201JSONResponse Product

func (response AddVariant201JSONResponse) VisitAddVariantResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type AddVariant400JSONResponse struct{ BadRequestJSONResponse }

func (response AddVariant400JSONResponse) VisitAddVariantResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type AddVariant401JSONResponse struct{ UnauthorizedJSONResponse }

func (response AddVariant401JSONResponse) VisitAddVariantResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type AddVariant404JSONResponse struct{ NotFoundJSONResponse }

func (response AddVariant404JSONResponse) VisitAddVariantResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type AddVariant409JSONResponse struct{ ConflictJSONResponse }

func (response AddVariant409JSONResponse) VisitAddVariantResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type DeleteVariantRequestObject struct {
	ProductUuid ProductUUID `json:"product_uuid"`
	VariantUuid VariantUUID `json:"variant_uuid"`
}

type DeleteVariantResponseObject interface {
	VisitDeleteVariantResponse(w http.ResponseWriter) error
}

type DeleteVariant200JSONResponse Product

func (response DeleteVariant200JSONResponse) VisitDeleteVariantResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type DeleteVariant400JSONResponse struct{ BadRequestJSONResponse }

func (response DeleteVariant400JSONResponse) VisitDeleteVariantResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type DeleteVariant401JSONResponse struct{ UnauthorizedJSONResponse }

func (response DeleteVariant401JSONResponse) VisitDeleteVariantResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type DeleteVariant404JSONResponse struct{ NotFoundJSONResponse }

func (response DeleteVariant404JSONResponse) VisitDeleteVariantResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type UpdateVariantRequestObject struct {
	ProductUuid ProductUUID `json:"product_uuid"`
	VariantUuid VariantUUID `json:"variant_uuid"`
	Body        *UpdateVariantJSONRequestBody
}

type UpdateVariantResponseObject interface {
	VisitUpdateVariantResponse(w http.ResponseWriter) error
}

type UpdateVariant200JSONResponse Product

func (response UpdateVariant200JSONResponse) VisitUpdateVariantResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpdateVariant400JSONResponse struct{ BadRequestJSONResponse }

func (response UpdateVariant400JSONResponse) VisitUpdateVariantResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type UpdateVariant401JSONResponse struct{ UnauthorizedJSONResponse }

func (response UpdateVariant401JSONResponse) VisitUpdateVariantResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type UpdateVariant404JSONResponse struct{ NotFoundJSONResponse }

func (response UpdateVariant404JSONResponse) VisitUpdateVariantResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type UpdateVariant409JSONResponse struct{ ConflictJSONResponse }

func (response UpdateVariant409JSONResponse) VisitUpdateVariantResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type UploadVariantImageRequestObject struct {
	ProductUuid ProductUUID `json:"product_uuid"`
	VariantUuid VariantUUID `json:"variant_uuid"`
	Params      UploadVariantImageParams
	Body        *multipart.Reader
}

type UploadVariantImageResponseObject interface {
	VisitUploadVariantImageResponse(w http.ResponseWriter) error
}

type UploadVariantImage201JSONResponse Product

func (response UploadVariantImage201JSONResponse) VisitUploadVariantImageResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type UploadVariantImage400JSONResponse struct{ BadRequestJSONResponse }

func (response UploadVariantImage400JSONResponse) VisitUploadVariantImageResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type UploadVariantImage401JSONResponse struct{ UnauthorizedJSONResponse }

func (response UploadVariantImage401JSONResponse) VisitUploadVariantImageResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type UploadVariantImage404JSONResponse struct{ NotFoundJSONResponse }

func (response UploadVariantImage404JSONResponse) VisitUploadVariantImageResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type DeleteVariantImageRequestObject struct {
	ProductUuid ProductUUID      `json:"product_uuid"`
	VariantUuid VariantUUID      `json:"variant_uuid"`
	ImageUuid   VariantImageUUID `json:"image_uuid"`
}

type DeleteVariantImageResponseObject interface {
	VisitDeleteVariantImageResponse(w http.ResponseWriter) error
}

type DeleteVariantImage200JSONResponse Product

func (response DeleteVariantImage200JSONResponse) VisitDeleteVariantImageResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type DeleteVariantImage400JSONResponse struct{ BadRequestJSONResponse }

func (response DeleteVariantImage400JSONResponse) VisitDeleteVariantImageResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type DeleteVariantImage401JSONResponse struct{ UnauthorizedJSONResponse }

func (response DeleteVariantImage401JSONResponse) VisitDeleteVariantImageResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type DeleteVariantImage404JSONResponse struct{ NotFoundJSONResponse }

func (response DeleteVariantImage404JSONResponse) VisitDeleteVariantImageResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// List all products
	// (GET /products)
	ListProducts(ctx context.Context, request ListProductsRequestObject) (ListProductsResponseObject, error)
	// Create a new product
	// (POST /products)
	CreateProduct(ctx context.Context, request CreateProductRequestObject) (CreateProductResponseObject, error)
	// Delete a product
	// (DELETE /products/{product_uuid})
	DeleteProduct(ctx context.Context, request DeleteProductRequestObject) (DeleteProductResponseObject, error)
	// Get product by UUID
	// (GET /products/{product_uuid})
	GetProduct(ctx context.Context, request GetProductRequestObject) (GetProductResponseObject, error)
	// Update product details
	// (PUT /products/{product_uuid})
	UpdateProduct(ctx context.Context, request UpdateProductRequestObject) (UpdateProductResponseObject, error)
	// Add a variant to a product
	// (POST /products/{product_uuid}/variants)
	AddVariant(ctx context.Context, request AddVariantRequestObject) (AddVariantResponseObject, error)
	// Delete a variant
	// (DELETE /products/{product_uuid}/variants/{variant_uuid})
	DeleteVariant(ctx context.Context, request DeleteVariantRequestObject) (DeleteVariantResponseObject, error)
	// Update a variant
	// (PUT /products/{product_uuid}/variants/{variant_uuid})
	UpdateVariant(ctx context.Context, request UpdateVariantRequestObject) (UpdateVariantResponseObject, error)
	// Upload a variant image
	// (POST /products/{product_uuid}/variants/{variant_uuid}/images)
	UploadVariantImage(ctx context.Context, request UploadVariantImageRequestObject) (UploadVariantImageResponseObject, error)
	// Delete a variant image
	// (DELETE /products/{product_uuid}/variants/{variant_uuid}/images/{image_uuid})
	DeleteVariantImage(ctx context.Context, request DeleteVariantImageRequestObject) (DeleteVariantImageResponseObject, error)
}

type StrictHandlerFunc = strictecho.StrictEchoHandlerFunc
type StrictMiddlewareFunc = strictecho.StrictEchoMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// ListProducts operation middleware
func (sh *strictHandler) ListProducts(ctx echo.Context) error {
	var request ListProductsRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListProducts(ctx.Request().Context(), request.(ListProductsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListProducts")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(ListProductsResponseObject); ok {
		return validResponse.VisitListProductsResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// CreateProduct operation middleware
func (sh *strictHandler) CreateProduct(ctx echo.Context) error {
	var request CreateProductRequestObject

	var body CreateProductJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateProduct(ctx.Request().Context(), request.(CreateProductRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateProduct")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(CreateProductResponseObject); ok {
		return validResponse.VisitCreateProductResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// DeleteProduct operation middleware
func (sh *strictHandler) DeleteProduct(ctx echo.Context, productUuid ProductUUID) error {
	var request DeleteProductRequestObject

	request.ProductUuid = productUuid

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteProduct(ctx.Request().Context(), request.(DeleteProductRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteProduct")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(DeleteProductResponseObject); ok {
		return validResponse.VisitDeleteProductResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetProduct operation middleware
func (sh *strictHandler) GetProduct(ctx echo.Context, productUuid ProductUUID) error {
	var request GetProductRequestObject

	request.ProductUuid = productUuid

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetProduct(ctx.Request().Context(), request.(GetProductRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetProduct")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetProductResponseObject); ok {
		return validResponse.VisitGetProductResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// UpdateProduct operation middleware
func (sh *strictHandler) UpdateProduct(ctx echo.Context, productUuid ProductUUID) error {
	var request UpdateProductRequestObject

	request.ProductUuid = productUuid

	var body UpdateProductJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateProduct(ctx.Request().Context(), request.(UpdateProductRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateProduct")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(UpdateProductResponseObject); ok {
		return validResponse.VisitUpdateProductResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// AddVariant operation middleware
func (sh *strictHandler) AddVariant(ctx echo.Context, productUuid ProductUUID) error {
	var request AddVariantRequestObject

	request.ProductUuid = productUuid

	var body AddVariantJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.AddVariant(ctx.Request().Context(), request.(AddVariantRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AddVariant")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(AddVariantResponseObject); ok {
		return validResponse.VisitAddVariantResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// DeleteVariant operation middleware
func (sh *strictHandler) DeleteVariant(ctx echo.Context, productUuid ProductUUID, variantUuid VariantUUID) error {
	var request DeleteVariantRequestObject

	request.ProductUuid = productUuid
	request.VariantUuid = variantUuid

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteVariant(ctx.Request().Context(), request.(DeleteVariantRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteVariant")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(DeleteVariantResponseObject); ok {
		return validResponse.VisitDeleteVariantResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// UpdateVariant operation middleware
func (sh *strictHandler) UpdateVariant(ctx echo.Context, productUuid ProductUUID, variantUuid VariantUUID) error {
	var request UpdateVariantRequestObject

	request.ProductUuid = productUuid
	request.VariantUuid = variantUuid

	var body UpdateVariantJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateVariant(ctx.Request().Context(), request.(UpdateVariantRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateVariant")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(UpdateVariantResponseObject); ok {
		return validResponse.VisitUpdateVariantResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// UploadVariantImage operation middleware
func (sh *strictHandler) UploadVariantImage(ctx echo.Context, productUuid ProductUUID, variantUuid VariantUUID, params UploadVariantImageParams) error {
	var request UploadVariantImageRequestObject

	request.ProductUuid = productUuid
	request.VariantUuid = variantUuid
	request.Params = params

	if reader, err := ctx.Request().MultipartReader(); err != nil {
		return err
	} else {
		request.Body = reader
	}

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UploadVariantImage(ctx.Request().Context(), request.(UploadVariantImageRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UploadVariantImage")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(UploadVariantImageResponseObject); ok {
		return validResponse.VisitUploadVariantImageResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// DeleteVariantImage operation middleware
func (sh *strictHandler) DeleteVariantImage(ctx echo.Context, productUuid ProductUUID, variantUuid VariantUUID, imageUuid VariantImageUUID) error {
	var request DeleteVariantImageRequestObject

	request.ProductUuid = productUuid
	request.VariantUuid = variantUuid
	request.ImageUuid = imageUuid

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteVariantImage(ctx.Request().Context(), request.(DeleteVariantImageRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteVariantImage")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(DeleteVariantImageResponseObject); ok {
		return validResponse.VisitDeleteVariantImageResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}
