// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: inventory.sql

package dbmodels

import (
	"context"
	"time"

	"jolly/backend/common"
)

const createReservation = `-- name: CreateReservation :exec
INSERT INTO inventory.reservations (reservation_uuid, order_uuid, created_at)
VALUES ($1, $2, $3)
`

type CreateReservationParams struct {
	ReservationUuid common.UUID
	OrderUuid       common.UUID
	CreatedAt       time.Time
}

func (q *Queries) CreateReservation(ctx context.Context, arg CreateReservationParams) error {
	_, err := q.db.Exec(ctx, createReservation, arg.ReservationUuid, arg.OrderUuid, arg.CreatedAt)
	return err
}

const createReservationItem = `-- name: CreateReservationItem :exec
INSERT INTO inventory.reservation_items (reservation_uuid, stock_uuid, quantity)
VALUES ($1, $2, $3)
`

type CreateReservationItemParams struct {
	ReservationUuid common.UUID
	StockUuid       common.UUID
	Quantity        int32
}

func (q *Queries) CreateReservationItem(ctx context.Context, arg CreateReservationItemParams) error {
	_, err := q.db.Exec(ctx, createReservationItem, arg.ReservationUuid, arg.StockUuid, arg.Quantity)
	return err
}

const getReservationForOrder = `-- name: GetReservationForOrder :one
SELECT reservation_uuid, order_uuid, created_at FROM inventory.reservations WHERE order_uuid = $1 LIMIT 1
`

func (q *Queries) GetReservationForOrder(ctx context.Context, orderUuid common.UUID) (InventoryReservation, error) {
	row := q.db.QueryRow(ctx, getReservationForOrder, orderUuid)
	var i InventoryReservation
	err := row.Scan(&i.ReservationUuid, &i.OrderUuid, &i.CreatedAt)
	return i, err
}

const getStockForUpdate = `-- name: GetStockForUpdate :one
SELECT stock_uuid, sku, quantity, created_at, updated_at FROM inventory.stocks WHERE sku = $1 FOR UPDATE
`

func (q *Queries) GetStockForUpdate(ctx context.Context, sku string) (InventoryStock, error) {
	row := q.db.QueryRow(ctx, getStockForUpdate, sku)
	var i InventoryStock
	err := row.Scan(
		&i.StockUuid,
		&i.Sku,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateStockQuantity = `-- name: UpdateStockQuantity :exec
UPDATE inventory.stocks SET quantity = $2, updated_at = NOW() WHERE stock_uuid = $1
`

type UpdateStockQuantityParams struct {
	StockUuid common.UUID
	Quantity  int32
}

func (q *Queries) UpdateStockQuantity(ctx context.Context, arg UpdateStockQuantityParams) error {
	_, err := q.db.Exec(ctx, updateStockQuantity, arg.StockUuid, arg.Quantity)
	return err
}

const upsertStock = `-- name: UpsertStock :one
INSERT INTO inventory.stocks (stock_uuid, sku, quantity, created_at, updated_at)
VALUES ($1, $2, $3, NOW(), NOW())
ON CONFLICT (sku) DO UPDATE
SET quantity = EXCLUDED.quantity, updated_at = NOW()
RETURNING stock_uuid, sku, quantity, created_at, updated_at
`

type UpsertStockParams struct {
	StockUuid common.UUID
	Sku       string
	Quantity  int32
}

func (q *Queries) UpsertStock(ctx context.Context, arg UpsertStockParams) (InventoryStock, error) {
	row := q.db.QueryRow(ctx, upsertStock, arg.StockUuid, arg.Sku, arg.Quantity)
	var i InventoryStock
	err := row.Scan(
		&i.StockUuid,
		&i.Sku,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
