// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbmodels

import (
	"time"

	"jolly/backend/common"
)

type InventoryReservation struct {
	ReservationUuid common.UUID
	OrderUuid       common.UUID
	CreatedAt       time.Time
}

type InventoryReservationItem struct {
	ReservationUuid common.UUID
	StockUuid       common.UUID
	Quantity        int32
}

type InventoryStock struct {
	StockUuid common.UUID
	Sku       string
	Quantity  int32
	CreatedAt time.Time
	UpdatedAt time.Time
}
