// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbmodels

import (
	"time"

	"jolly/backend/products/domain"
)

type ProductsProduct struct {
	ProductUuid domain.ProductUUID
	Name        string
	Description string
	Status      domain.ProductStatus
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type ProductsVariant struct {
	VariantUuid domain.VariantUUID
	ProductUuid domain.ProductUUID
	Sku         string
	Name        string
	PriceCents  int64
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type ProductsVariantImage struct {
	ImageUuid   domain.VariantImageUUID
	VariantUuid domain.VariantUUID
	Url         string
	Position    int32
	CreatedAt   time.Time
}
