// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: products.sql

package dbmodels

import (
	"context"
	"time"

	"jolly/backend/products/domain"
)

const createProduct = `-- name: CreateProduct :exec
INSERT INTO products.products (
	product_uuid,
	name,
	description,
	status,
	created_at,
	updated_at
)
VALUES
	($1, $2, $3, $4, $5, $6)
`

type CreateProductParams struct {
	ProductUuid domain.ProductUUID
	Name        string
	Description string
	Status      domain.ProductStatus
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) error {
	_, err := q.db.Exec(ctx, createProduct,
		arg.ProductUuid,
		arg.Name,
		arg.Description,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createVariant = `-- name: CreateVariant :exec
INSERT INTO products.variants (
	variant_uuid,
	product_uuid,
	sku,
	name,
	price_cents,
	created_at,
	updated_at
)
VALUES
	($1, $2, $3, $4, $5, $6, $7)
`

type CreateVariantParams struct {
	VariantUuid domain.VariantUUID
	ProductUuid domain.ProductUUID
	Sku         string
	Name        string
	PriceCents  int64
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) CreateVariant(ctx context.Context, arg CreateVariantParams) error {
	_, err := q.db.Exec(ctx, createVariant,
		arg.VariantUuid,
		arg.ProductUuid,
		arg.Sku,
		arg.Name,
		arg.PriceCents,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createVariantImage = `-- name: CreateVariantImage :exec
INSERT INTO products.variant_images (
	image_uuid,
	variant_uuid,
	url,
	position,
	created_at
)
VALUES
	($1, $2, $3, $4, $5)
`

type CreateVariantImageParams struct {
	ImageUuid   domain.VariantImageUUID
	VariantUuid domain.VariantUUID
	Url         string
	Position    int32
	CreatedAt   time.Time
}

func (q *Queries) CreateVariantImage(ctx context.Context, arg CreateVariantImageParams) error {
	_, err := q.db.Exec(ctx, createVariantImage,
		arg.ImageUuid,
		arg.VariantUuid,
		arg.Url,
		arg.Position,
		arg.CreatedAt,
	)
	return err
}

const deleteImagesForVariant = `-- name: DeleteImagesForVariant :exec
DELETE FROM products.variant_images
WHERE
	variant_uuid = $1
`

func (q *Queries) DeleteImagesForVariant(ctx context.Context, variantUuid domain.VariantUUID) error {
	_, err := q.db.Exec(ctx, deleteImagesForVariant, variantUuid)
	return err
}

const deleteProduct = `-- name: DeleteProduct :exec
DELETE FROM products.products
WHERE
	product_uuid = $1
`

func (q *Queries) DeleteProduct(ctx context.Context, productUuid domain.ProductUUID) error {
	_, err := q.db.Exec(ctx, deleteProduct, productUuid)
	return err
}

const deleteVariant = `-- name: DeleteVariant :exec
DELETE FROM products.variants
WHERE
	variant_uuid = $1
`

func (q *Queries) DeleteVariant(ctx context.Context, variantUuid domain.VariantUUID) error {
	_, err := q.db.Exec(ctx, deleteVariant, variantUuid)
	return err
}

const deleteVariantImage = `-- name: DeleteVariantImage :exec
DELETE FROM products.variant_images
WHERE
	image_uuid = $1
`

func (q *Queries) DeleteVariantImage(ctx context.Context, imageUuid domain.VariantImageUUID) error {
	_, err := q.db.Exec(ctx, deleteVariantImage, imageUuid)
	return err
}

const deleteVariantsForProduct = `-- name: DeleteVariantsForProduct :exec
DELETE FROM products.variants
WHERE
	product_uuid = $1
`

func (q *Queries) DeleteVariantsForProduct(ctx context.Context, productUuid domain.ProductUUID) error {
	_, err := q.db.Exec(ctx, deleteVariantsForProduct, productUuid)
	return err
}

const getImagesForVariant = `-- name: GetImagesForVariant :many
SELECT
	image_uuid, variant_uuid, url, position, created_at
FROM
	products.variant_images
WHERE
	variant_uuid = $1
ORDER BY
	position ASC
`

func (q *Queries) GetImagesForVariant(ctx context.Context, variantUuid domain.VariantUUID) ([]ProductsVariantImage, error) {
	rows, err := q.db.Query(ctx, getImagesForVariant, variantUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProductsVariantImage{}
	for rows.Next() {
		var i ProductsVariantImage
		if err := rows.Scan(
			&i.ImageUuid,
			&i.VariantUuid,
			&i.Url,
			&i.Position,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProduct = `-- name: GetProduct :one
SELECT
	product_uuid, name, description, status, created_at, updated_at
FROM
	products.products
WHERE
	product_uuid = $1
LIMIT 1
`

func (q *Queries) GetProduct(ctx context.Context, productUuid domain.ProductUUID) (ProductsProduct, error) {
	row := q.db.QueryRow(ctx, getProduct, productUuid)
	var i ProductsProduct
	err := row.Scan(
		&i.ProductUuid,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVariantBySKU = `-- name: GetVariantBySKU :one
SELECT
	variant_uuid, product_uuid, sku, name, price_cents, created_at, updated_at
FROM
	products.variants
WHERE
	sku = $1
LIMIT 1
`

func (q *Queries) GetVariantBySKU(ctx context.Context, sku string) (ProductsVariant, error) {
	row := q.db.QueryRow(ctx, getVariantBySKU, sku)
	var i ProductsVariant
	err := row.Scan(
		&i.VariantUuid,
		&i.ProductUuid,
		&i.Sku,
		&i.Name,
		&i.PriceCents,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVariantsForProduct = `-- name: GetVariantsForProduct :many
SELECT
	variant_uuid, product_uuid, sku, name, price_cents, created_at, updated_at
FROM
	products.variants
WHERE
	product_uuid = $1
ORDER BY
	created_at ASC
`

func (q *Queries) GetVariantsForProduct(ctx context.Context, productUuid domain.ProductUUID) ([]ProductsVariant, error) {
	rows, err := q.db.Query(ctx, getVariantsForProduct, productUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProductsVariant{}
	for rows.Next() {
		var i ProductsVariant
		if err := rows.Scan(
			&i.VariantUuid,
			&i.ProductUuid,
			&i.Sku,
			&i.Name,
			&i.PriceCents,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProducts = `-- name: ListProducts :many
SELECT
	product_uuid, name, description, status, created_at, updated_at
FROM
	products.products
ORDER BY
	created_at DESC
`

func (q *Queries) ListProducts(ctx context.Context) ([]ProductsProduct, error) {
	rows, err := q.db.Query(ctx, listProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProductsProduct{}
	for rows.Next() {
		var i ProductsProduct
		if err := rows.Scan(
			&i.ProductUuid,
			&i.Name,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :exec
UPDATE products.products
SET
	name = $2,
	description = $3,
	status = $4,
	updated_at = $5
WHERE
	product_uuid = $1
`

type UpdateProductParams struct {
	ProductUuid domain.ProductUUID
	Name        string
	Description string
	Status      domain.ProductStatus
	UpdatedAt   time.Time
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) error {
	_, err := q.db.Exec(ctx, updateProduct,
		arg.ProductUuid,
		arg.Name,
		arg.Description,
		arg.Status,
		arg.UpdatedAt,
	)
	return err
}

const updateVariant = `-- name: UpdateVariant :exec
UPDATE products.variants
SET
	sku = $2,
	name = $3,
	price_cents = $4,
	updated_at = $5
WHERE
	variant_uuid = $1
`

type UpdateVariantParams struct {
	VariantUuid domain.VariantUUID
	Sku         string
	Name        string
	PriceCents  int64
	UpdatedAt   time.Time
}

func (q *Queries) UpdateVariant(ctx context.Context, arg UpdateVariantParams) error {
	_, err := q.db.Exec(ctx, updateVariant,
		arg.VariantUuid,
		arg.Sku,
		arg.Name,
		arg.PriceCents,
		arg.UpdatedAt,
	)
	return err
}
